-- Active: 1677234517062@@127.0.0.1@3306@db_TodoApp

CREATE DATABASE db_TodoApp;

USE db_TodoApp;

DROP TABLE IF EXISTS Usuarios;

CREATE TABLE
    Usuarios(
        PK_ID INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
        USUARIO VARCHAR(25) NOT NULL,
        CONTRASENA VARCHAR(50) NOT NULL,
        PRIMARY KEY(PK_ID)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

INSERT INTO
    Usuarios(USUARIO, CONTRASENA)
VALUES("JEFFERSON", "12345");

SELECT * from Usuarios;